jobs:
  - ${{ each vmImage in parameters.vmImages }}:
    - ${{ each pythonVersion in parameters.pythonVersions }}:
        - job:
          displayName: ${{ format('OS:{0} PY:{1}', vmImage, pythonVersion) }}
          pool:
            vmImage: ${{ vmImage }}

          steps:
          - task: UsePythonVersion@0
            inputs:
              versionSpec: '${{ pythonVersion }}'

          - script: |
              brew install graphviz
            displayName: 'Install dependencies'

          - script: |
              pip install --use-pep517 "jericho>=.dev"
            condition: eq(variables.installFromSource, false)
            displayName: 'Install a prerelease of Jericho from PyPi'

          - script: |
              pip install -e .
            condition: eq(variables.installFromSource, true)
            displayName: 'Install Jericho from source'

          - script: |
              pip install pytest pytest-azurepipelines pytest-cov
              pytest --junitxml=junit/test-results.xml --cov=jericho --cov-report=xml --cov-report=html tests/ jericho/
            displayName: 'Run tests'

          - task: PublishCodeCoverageResults@1
            inputs:
                codeCoverageTool: Cobertura
                summaryFileLocation: '$(System.DefaultWorkingDirectory)/**/coverage.xml'
                reportDirectory: '$(System.DefaultWorkingDirectory)/**/htmlcov'
